site_name: Your Project Name
theme:
  name: material

# 版本设置
extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Usage: guide/usage.md
  - API Reference: api.md